[[constraint]]
  name = "github.com/spf13/cobra"
  revision = "7547e83b2d85fd1893c7d76916f67689d761fecb"

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "v1.3.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name ="github.com/hashicorp/go-multierror"
  version = "v1.0.0"

[prune]
  go-tests = true
  unused-packages = true
